version: '3.7'

services:
  tomcat:
    image: "jsp-app-1-2:latest"
    ports:
      - "5000:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    networks:
      - net-1
    deploy:
      replicas: 1
      depends_on:
        mysql:
          condition: service_healthy

  mysql:
    image: "mysql:8.0"
    ports:
      - '3306:33060'
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-data-import:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/db_table.sql --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: jspDiary
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    networks:
      - net-1
    deploy:
      replicas: 1
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "test_user", "-p${MYSQL_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 3

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    networks:
      - net-1
    deploy:
      replicas: 1
    volumes:
      - /opt/docker/test-1/nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - net-1
    deploy:
      replicas: 1
      depends_on:
        mysql:
          condition: service_healthy

volumes:
  mysql-data:
  mysql-data-import:
  
networks:
  net-1:
    external: true
